apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
      - name: platform
        image: ghcr.io/kevinpan45/platform:0.0.1-SNAPSHOT
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
